In [1]:
import numpy as np

In [6]:
arr=np.array([1])

In [7]:
arr.dtype

dtype('int32')

In [8]:
lst=[1,2,3,4,5]
print(lst)
print(type(lst))

[1, 2, 3, 4, 5]
<class 'list'>


In [10]:
arr=np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
arr.shape

(5,)

In [15]:
arr.ndim

1

In [16]:
arr.size

5

In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(type(arr))
print('Shape: ',arr.shape)
print('Size(No of elements): ',arr.size)
print('Dimensions: ',arr.ndim)


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Shape:  (2, 3)
Size(No of elements):  6
Dimensions:  2


In [20]:
my_lst=[[1,2,3,4],[4,5,6,7],[7,8,9,10]]
print(my_lst)
print(type(my_lst))

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]]
<class 'list'>


In [24]:
b=np.array(my_lst)
print(b)
print(type(b))
print('Shape: ',b.shape)
print('Size(No of elements): ',b.size)
print('Dimensions: ',b.ndim)


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
<class 'numpy.ndarray'>
Shape:  (3, 4)
Size(No of elements):  12
Dimensions:  2


In [27]:
my_lst=[[[1,2,3],[4,5,6]],[[8,6,4],[3,7,5]],[[2,5,9],[0,4,8]]]
print(my_lst)

[[[1, 2, 3], [4, 5, 6]], [[8, 6, 4], [3, 7, 5]], [[2, 5, 9], [0, 4, 8]]]


In [41]:
x=np.array(my_lst)
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[[[1 2 3]
  [4 5 6]]

 [[8 6 4]
  [3 7 5]]

 [[2 5 9]
  [0 4 8]]]
3
(3, 2, 3)
18
int32


In [42]:
nw=np.arange(24).reshape((2,3,4))

In [43]:
nw

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [44]:
nw.max(axis=1)      # Column with max sum

array([[ 8,  9, 10, 11],
       [20, 21, 22, 23]])

In [45]:
nw.max(axis=0)      # Row with max sum

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
nw.sum(axis=0)      # sumation of each 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
np.arange(2,100,4)

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [58]:
df=np.arange(24).reshape(8,3)
df


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## BroadCasting

In [72]:
bg=np.ones((3,4),dtype='int')
print(bg)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [73]:
bg.dtype

dtype('int32')

In [74]:
bg*3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

## Random Number Generation

In [84]:
np.random.rand(10,2)      # random samples from uniform dist ranges from [0,1)

array([[0.07090601, 0.05587993],
       [0.02728147, 0.91788715],
       [0.28578768, 0.74608585],
       [0.17931064, 0.8272255 ],
       [0.34764158, 0.05626897],
       [0.19596715, 0.07976341],
       [0.63027397, 0.47836743],
       [0.29274439, 0.5025024 ],
       [0.4768335 , 0.28210904],
       [0.34221765, 0.50528304]])

In [92]:
np.random.randn(10)       # random samples from std normal dist ranges from -3 to +3

array([ 1.6342184 , -0.08271339, -0.99972447, -0.5748229 , -0.41206981,
       -0.45668365, -0.83342429,  0.59558876, -0.52867647,  0.96276241])

In [105]:
marks=np.random.randint(60,101,65)

In [107]:
marks.max()

100

In [108]:
marks.argmax()    

30

## Indexing and Selection

In [4]:
x=np.arange(10,100,7)
print(x)

[10 17 24 31 38 45 52 59 66 73 80 87 94]


In [15]:
print('Length: ',len(x))
print('First Element: ',x[0])
print('Last Element: ',x[-1])
print('Alternate elements at even position: ',x[0::2])
print('Alternate elements at odd position: ',x[1::2])
print('Reverse List: ',x[::-1])

Length:  13
First Element:  10
Last Element:  94
Alternate elements at even position:  [10 24 38 52 66 80 94]
Alternate elements at odd position:  [17 31 45 59 73 87]
Reverse List:  [94 87 80 73 66 59 52 45 38 31 24 17 10]


## Filtering

In [24]:
x=np.random.randint(0,500,20)
print(x)

[ 64 185 149 337 418  28 231 142 265 237  58 310  65 179  30 187 143 494
  17 150]


In [25]:
x<100

array([ True, False, False, False, False,  True, False, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True, False])

In [26]:
np.where(x<100)

(array([ 0,  5, 10, 12, 14, 18], dtype=int64),)

In [28]:
x=np.random.randint(0,500,25).reshape((5,5))
print(x)

[[165 480 293 438  65]
 [406 345 281 325 491]
 [449 108 335 451  22]
 [ 48 271 303 101 386]
 [373 120 133  72 461]]


In [31]:
x[1::2,1::2]

array([[345, 325],
       [271, 101]])

In [33]:
x[:,:2]           

array([[165, 480],
       [406, 345],
       [449, 108],
       [ 48, 271],
       [373, 120]])

In [34]:
x[,]

SyntaxError: invalid syntax (2630041655.py, line 1)

In [35]:
x=np.random.randint(0,100,100).reshape((10,10))
x

array([[50, 73, 44, 88, 87, 62, 93, 65, 29, 89],
       [43, 74,  0, 23, 45, 45, 46,  5, 39, 68],
       [91, 50, 83, 99, 88, 26, 75, 50, 58, 80],
       [89, 49, 69, 96, 77, 35, 69,  2, 62, 99],
       [48, 23, 70,  7, 28, 21, 41, 67, 87, 94],
       [44,  8, 71, 36, 70, 86, 92,  2, 77, 38],
       [89, 35, 13, 54, 85, 21, 69, 51, 56, 70],
       [39, 50, 41, 88, 79, 65, 40, 25, 11,  1],
       [48, 28, 10, 77, 63, 35, 93, 84, 72, 53],
       [85, 10,  5, 14, 32, 24, 73, 62, 97, 14]])

In [39]:
x[0]=np.arange(1,11)

In [40]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [43, 74,  0, 23, 45, 45, 46,  5, 39, 68],
       [91, 50, 83, 99, 88, 26, 75, 50, 58, 80],
       [89, 49, 69, 96, 77, 35, 69,  2, 62, 99],
       [48, 23, 70,  7, 28, 21, 41, 67, 87, 94],
       [44,  8, 71, 36, 70, 86, 92,  2, 77, 38],
       [89, 35, 13, 54, 85, 21, 69, 51, 56, 70],
       [39, 50, 41, 88, 79, 65, 40, 25, 11,  1],
       [48, 28, 10, 77, 63, 35, 93, 84, 72, 53],
       [85, 10,  5, 14, 32, 24, 73, 62, 97, 14]])

In [42]:
X[:,]

10

In [44]:
arr=np.zeros((10,10))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
j=0
for i in range(x.shape[0]):
    arr[i]=np.arange(j+1,j+11)
    j+=10
arr

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [48]:
arr[[1,4,7]]

array([[11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.],
       [71., 72., 73., 74., 75., 76., 77., 78., 79., 80.]])

In [52]:
arr[::,4::5]

array([[  5.,  10.],
       [ 15.,  20.],
       [ 25.,  30.],
       [ 35.,  40.],
       [ 45.,  50.],
       [ 55.,  60.],
       [ 65.,  70.],
       [ 75.,  80.],
       [ 85.,  90.],
       [ 95., 100.]])